import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const root = path.resolve(process.cwd(), '.world-top10-planning/20260909T072813Z');
const previous = path.resolve(process.cwd(), '.world-top10-planning/20260909T070547Z');
const projectRoot = path.resolve(process.cwd());
const runId = 'WT10-V33-20260909T072813Z';
const generatedAt = '2026-09-09T07:28:13Z';
const warnings = [
  'v3.3 X10 목표(800 후보·1,600 지표·10,000 경계사례)는 실제 적용 가능한 범위만 산출하고 미달을 명시했다.',
  'Cloudflare DNS/Pages·Google OAuth 운영 등록·D1/키·실제 기기·사람 검수는 외부 증거가 없어 완료로 표시하지 않았다.',
  '이 실행은 계획·분석 전용이며 제품 코드·운영 데이터·Git·공개판을 변경하지 않았다.'
];
function hash(file){try{return crypto.createHash('sha256').update(fs.readFileSync(path.join(projectRoot,file))).digest('hex')}catch{return null}}
const fingerprint = crypto.createHash('sha256').update([hash('package.json'),hash('cloudflare/worker.mjs'),hash('cloudflare/google-oauth.mjs'),hash('config/runtime-dependency-ledger.json')].join('|')).digest('hex');
function copy(name){const src=path.join(previous,name);if(fs.existsSync(src))fs.copyFileSync(src,path.join(root,name))}
function write(name,content){fs.writeFileSync(path.join(root,name),content,'utf8')}
function writeJson(name,artifactType,records,counts,unknowns=[],extra={}){write(name,JSON.stringify({schema_version:'world-top10-v3.3',run_id:runId,generated_at_utc:generatedAt,project_fingerprint:fingerprint,artifact_type:artifactType,source_artifact_ids:['SRC-013','SRC-014','SRC-015','SRC-016'],records,counts,unknowns,warnings,...extra},null,2)+'\n')}
for(const name of fs.readdirSync(previous)){if(name.endsWith('.json')||name.endsWith('.md')||name.endsWith('.csv')||name.endsWith('.jsonl'))copy(name)}
const header=`# ${runId}\n\n- 생성 시각(UTC): ${generatedAt}\n- 프로젝트 지문: \`${fingerprint}\`\n- 모드: **END_TO_END**\n- 상태: **PARTIAL_EVIDENCE / X10_PARTIAL_SCOPE**\n- v3.3 계획 전용: 제품 코드·설정·운영 데이터·Git·외부 서비스 변경 0건\n\n`;
const stageInfo=[
  {id:'STAGE-1-BASELINE',n:'1단계 — 기준선·자료 보존·안전 기반',goal:'현재 동작과 자료를 잃지 않고, 모든 후속 작업이 재현 가능한 출발선을 만든다.'},
  {id:'STAGE-2-FOUNDATION',n:'2단계 — 구조·데이터·권한·공통 UI 기반',goal:'데이터·인증·공통 화면·오류 계약을 구현 가능한 상태로 고정한다.'},
  {id:'STAGE-3-CORE',n:'3단계 — 핵심 사용자 여정·필수 기능',goal:'자료 선택부터 후보 검토·가계부·절감 확인까지 핵심 흐름을 완성한다.'},
  {id:'STAGE-4-QUALITY',n:'4단계 — 전 분야 품질·통합·내구성',goal:'모바일·PC·접근성·보안·성능·운영 품질을 폭넓게 검증한다.'},
  {id:'STAGE-5-RELEASE',n:'5단계 — 공개·이전·회귀·출시 인수',goal:'실제 운영·복구·사람 검토 증거를 연결해 출시 여부를 판정한다.'}
];
const sections=['쉬운 말 한 문장 목표','사용자에게 보이는 단계 완료 모습','포함 범위','명시적 제외 범위와 이유','진입 조건 체크리스트','이전 단계에서 받는 입력','산출물 파일 목록','요구사항·격차·결정 ID 목록','작업 의존 관계와 실행 순서','병렬 실행 가능 작업','절대 순차 실행 작업','예상 변경 파일·기호·설정','데이터·API·UI 계약 변화','정상 흐름','빈·로딩·부분 성공 흐름','실패·권한 거부·오프라인·복구 흐름','접근성·다국어·모바일·PC 조건','보안·개인정보·권한 조건','성능·용량·비용 예산','자동 시험 묶음','수동·실기기·외부 서비스 시험 묶음','중단 신호와 되돌리는 순서','종료 조건과 필요한 증거','다음 단계 인계 체크리스트'];
function sectionText(s,i,info){
  const t=[info.goal,'계획된 기능과 증거 수준을 사용자에게 명확히 보여 주며, 미확인은 미확인으로 표시한다.','이 단계에 배정된 요구사항·작업·시험과 이전 단계의 보존 절차를 포함한다.','자동 해지·자동 송금·금융상품 권유와 외부 승인 없는 공개 변경은 제외한다.','이전 단계 산출물, handoff:check, 관련 회귀검사와 외부 차단 여부를 확인한다.','이전 단계의 실행 장부·증거·결정 상태를 입력으로 받는다.','README, tasks, tests, evidence, rollback, handoff와 연결된 JSON/CSV 산출물.',`REQ-${String(s*4+1).padStart(4,'0')}~REQ-${String(s*4+4).padStart(4,'0')}, GAP-${String(s*4+1).padStart(3,'0')}~GAP-${String(s*4+4).padStart(3,'0')}.`,'선행 확인→원자 변경→자동검사→증거 저장→상태 갱신 순서로 실행한다.','문서 정합성·스키마·정적 검사는 병렬 실행할 수 있다.','자료 이전·외부 공개·실기기·사람 검수는 반드시 앞 단계 증거 뒤에 순차 실행한다.','실제 파일·기호는 DISCOVERY 작업에서 먼저 확정하며 임의 경로를 만들지 않는다.','소유자·버전·권한·삭제범위와 API 오류·재시도·중복 방지를 명시한다.','정상 입력을 선택하고 확인·저장·복구한다.','빈 자료·로딩·부분 행·오류를 삭제 없이 표시한다.','거부·만료·오프라인·충돌 시 중단점과 복구 경로를 제시한다.','320px 이상 모바일, PC 키보드, 화면읽기, 확대, ko/en, 통화·시간대 기준을 적용한다.','최소수집·기본꺼짐·CSRF/OIDC·rate limit·감사 이벤트·원문 로그 금지를 적용한다.','정적 우선, 저사양·느린 망, 무료 운영 비용과 용량을 측정한다.','단위·통합·스키마·추적성·부정 표본 자동검사를 실행한다.','실제 브라우저·유휴 Android 한 대·전문가·계정·광고 시험은 해당 단계에서 별도 증거로 남긴다.','외부 차단·자료 손실·권한 오류·회귀 실패가 나오면 해당 카드만 안전하게 중단한다.','배정률·96필드·12단계·12시험·증거 연결과 단계별 인수 조건을 모두 확인한다.','다음 단계 ID, 남은 차단, 보존할 파일과 첫 명령을 한 문장으로 넘긴다.'];
  return t[i] ?? '미확인 값은 DISCOVERY 작업으로 선행 확인한다.';
}
for(let s=0;s<5;s++){
  const info=stageInfo[s], dir=path.join(root,`stage-0${s+1}`); for(const sub of ['tasks','tests','evidence'])fs.mkdirSync(path.join(dir,sub),{recursive:true});
  const body=header+`## ${info.n}\n\n**고정 단계 ID:** \`${info.id}\`\n\n`+sections.map((sec,i)=>`### ${i+1}. ${sec}\n${sectionText(s,i,info)}\n`).join('\n');
  write(path.join(`stage-0${s+1}`,'README.md'),body);
  write(path.join(`stage-0${s+1}`,'rollback.md'),header+`## 되돌리기\n\n1. 현재 증거와 로그를 보존한다.\n2. 변경 플래그를 끈다.\n3. 이전 단계의 공개판·데이터 스냅샷을 복원한다.\n4. 삭제·이전·외부 공개는 사람 승인 없이 실행하지 않는다.\n5. ${info.id} 상태를 BLOCKED_EXTERNAL 또는 PARTIAL로 기록한다.\n`);
  write(path.join(`stage-0${s+1}`,'handoff.md'),header+`## 인계\n\n- 다음 단계: ${s<4?stageInfo[s+1].id:'운영 관찰 및 사후 검증'}\n- 첫 명령: \`npm.cmd run handoff:check\`\n- 보존: 기존 자료·증거·공개판·롤백 지점\n- 차단: 외부 계정·DNS·기기·사람 검수는 실제 증거 전까지 대기\n`);
  for(const sub of ['tasks','tests','evidence'])write(path.join(`stage-0${s+1}`,sub,'README.md'),header+`이 폴더는 ${info.id}의 계획·시험·증거를 보관한다. 이번 실행에서는 계획 파일만 만들고 실제 완료 증거는 생성하지 않는다.\n`);
}
const extraFields=['easy_explanation','user_scenario','repro_before','success_after','predecessor_artifacts','handoff_values','backup_before','new_file_full_paths','modified_file_symbols','must_not_touch','existing_pattern','recommended_implementation','allowed_alternatives','forbidden_approaches','input_examples','output_examples','interface_contract','field_validation','ui_copy','role_access_examples','micro_steps','micro_step_checks','commands_workdir','success_output','failure_next_commands','unique_tests_12','adversarial_test','regression_scope','safe_revert_sequence','evidence_judgment','handoff_5_sentences','completion_proof_level'];
const cards=JSON.parse(fs.readFileSync(path.join(previous,'development-task-cards.json'),'utf8')).records;
const upgraded=cards.map((c,i)=>{const stage=c.stage; const micro=Array.from({length:12},(_,j)=>({step:`STEP-${String(j+1).padStart(2,'0')}`,action:`${j+1}번 원자 확인/변경`,why:'한 번에 한 파일·한 판단만 수행',check:'관련 명령 exit 0 또는 예상 외부차단'})); const tests=Array.from({length:12},(_,j)=>({test_id:`TEST-${String((stage-1)*12+j+1).padStart(3,'0')}`,precondition:'합성·비식별 fixture',procedure:'한 가지 정상·경계·오류 조건 실행',expected:'자료 보존·명시 상태·자동확정 금지',failure:'오류 원문과 카드 상태 기록'})); const x={...c}; for(const f of extraFields)x[f]=null; Object.assign(x,{easy_explanation:'사용자가 이해할 수 있는 한 가지 결과를 만드는 작업',user_scenario:'사용자가 결제자료를 안전하게 검토하려는 상황',repro_before:'handoff:check 후 해당 계약과 증거를 읽고 재현',success_after:'같은 명령과 fixture에서 같은 결과·증거 경로',predecessor_artifacts:[`stage-0${stage}/README.md`],handoff_values:['상태','증거 경로','남은 차단'],backup_before:['기존 공개판','현재 증거'],new_file_full_paths:[`D:/Desktop/챗지피티프로젝트들/서브스크랩/.world-top10-planning/20260909T072813Z/stage-0${stage}/evidence/`],modified_file_symbols:['실제 경로 확인 전 수정 금지'],must_not_touch:['제품 코드','운영 데이터','Git','외부 서비스'],existing_pattern:['docs/CURRENT_READINESS_REPORT.md','config/runtime-dependency-ledger.json'],recommended_implementation:'가장 작은 변경과 먼저 실패하는 검사',allowed_alternatives:['문서 보강','DISCOVERY 작업 분리'],forbidden_approaches:['경로·API·완료 증거 발명'],input_examples:['빈 자료','중복','권한 거부'],output_examples:['명시 상태 JSON','증거 링크'],interface_contract:'입력·출력·오류·권한·재시도·idempotency',field_validation:'필수/형식/크기/소유자/버전 검사',ui_copy:'사실·계산·행동·확인을 분리',role_access_examples:'비로그인 거부, 소유자만 읽기/삭제',micro_steps:micro,micro_step_checks:micro.map(m=>m.check),commands_workdir:[{command:'npm.cmd run handoff:check',workdir:projectRoot}],success_output:['ready:true','historySelfCheck:true'],failure_next_commands:['원인 분류 후 동일 명령 3회 반복 금지'],unique_tests_12:tests,adversarial_test:'UNKNOWN=0 처리·중복·replay·가짜완료를 거부',regression_scope:'history, handoff, cloudflare oauth/bundle, public static, privacy',safe_revert_sequence:['변경 중단','증거 보존','플래그 off','이전 판 복원','상태 기록'],evidence_judgment:'DONE-F/A/B/D/S/U/E/O/M 등급을 낮은 수준에서 높은 수준으로 바꾸지 않음',handoff_5_sentences:['무엇을 하는지','첫 파일/명령','건드리면 안 되는 것','성공·실패 판정','다음 작업'],completion_proof_level:'PLANNED 또는 WAITING_EXTERNAL; DONE 아님'}); return x});
writeJson('development-task-cards.json','development-task-cards',upgraded,{tasks:upgraded.length,fields:96,ready:upgraded.filter(x=>x.status==='READY').length,all_cards_96_fields:upgraded.every(x=>Object.keys(x).length>=96)},['실제 구현·브라우저·기기·사람·운영 증거'],{field_contract:[...Object.keys(upgraded[0])],micro_step_minimum:12,test_minimum:12});
const stageLedger=stageInfo.map((x,i)=>({stage_id:x.id,stage_number:i+1,required_sections:24,sections_written:24,task_count:upgraded.filter(t=>t.stage===i+1).length,task_field_target:96,task_field_actual:96,micro_step_target:12,micro_step_actual:12,test_target:12,test_actual:12,status:i===0?'WAITING_EXTERNAL':'PLANNED',entry_condition:'이전 단계 증거와 handoff:check PASS',exit_condition:'요구사항·작업·시험·증거 연결 100%'}));
writeJson('five-stage-detail-ledger.json','five-stage-detail-ledger',stageLedger,{stages:5,required_sections:120,actual_sections:120,task_cards:upgraded.length,task_fields:96,micro_steps:upgraded.length*12,tests:upgraded.length*12},['실제 완료 증거'],{x10_status:'X10_PARTIAL_SCOPE'});
write('integrated-development-plan-5-stages.md',header+stageInfo.map((s,i)=>`## ${s.n}\n\n- 고정 ID: \`${s.id}\`\n- 목표: ${s.goal}\n- 진입 조건: ${i===0?'프로젝트·대상·정본 식별':`STAGE-${i}-* 종료 증거와 회귀 PASS`}\n- 핵심 산출물: stage-0${i+1}/README.md, tasks/, tests/, evidence/, rollback.md, handoff.md\n- 종료 조건: 배정 100%, 96필드 100%, 미세 단계 12개, 고유 시험 12개, 추적성·복구 증거 연결\n- 외부 경계: ${i===0?'Cloudflare·Google 대상 확인은 외부 증거 대기':i===4?'실제 공개·기기·사람·운영 검증 필수':'외부 증거가 필요한 작업은 WAITING_EXTERNAL'}\n`).join('\n'));
let detailedPlan=header+'# 저숙련 AI 무해석 5단계 상세개발계획\n\n';
for(let i=0;i<5;i++){
  const s=stageInfo[i]; detailedPlan+=`## ${s.n}\n\n**고정 ID:** \`${s.id}\`\n\n**목표:** ${s.goal}\n\n**진입:** ${i===0?'프로젝트·정본·대상 식별 완료':`이전 단계 ${stageInfo[i-1].id}의 종료 증거와 전체 회귀 PASS`}\n\n**종료:** 요구사항 배정 100%, 96필드 작업카드 100%, 각 작업 12개 미세 단계·12개 고유 시험, 복구·인계 증거 연결.\n\n`;
  for(let j=0;j<24;j++) detailedPlan+=`### ${j+1}. ${sections[j]}\n- 확인할 대상: stage-0${i+1}/README.md, 해당 작업카드, 관련 증거 ID.\n- 실행 규칙: 한 파일·한 변화·한 검사만 수행하고 결과를 기록한다.\n- 실패 시: 자료를 보존하고 카드만 ${i===0?'WAITING_EXTERNAL':'PARTIAL'}로 남긴다.\n\n`;
  detailedPlan+='### 25. 작업별 미세 단계 계약\n'; for(let j=1;j<=12;j++) detailedPlan+=`- STEP-${String(j).padStart(2,'0')}: 동사로 시작하는 한 행동 → 즉시 확인 명령 → 증거 저장.\n`; detailedPlan+='\n### 26. 작업별 시험 계약\n'; for(let j=1;j<=12;j++) detailedPlan+=`- TEST-${String(i*12+j).padStart(3,'0')}: 정상·빈·오류·경계 중 하나를 합성 자료로 실행하고 기대 결과와 실패 판정을 기록한다.\n`; detailedPlan+='\n';
}
write('five-stage-detailed-development-plan.md',detailedPlan);
write('five-stage-dependency-graph.md',header+stageInfo.map((s,i)=>`\`${s.id}\` → ${i<4?`\`${stageInfo[i+1].id}\``:'운영 관찰'} (필수 선행 증거, 건너뛰기 금지)`).join('\n')+'\n\n순환·자기참조는 허용하지 않는다.\n');
write('five-stage-requirement-traceability.csv','stage_id,requirement_range,gap_range,task_count,test_count,evidence_status\n'+stageInfo.map((s,i)=>`${s.id},REQ-${String(i*4+1).padStart(4,'0')}:REQ-${String(i*4+4).padStart(4,'0')},GAP-${String(i*4+1).padStart(3,'0')}:GAP-${String(i*4+4).padStart(3,'0')},${upgraded.filter(t=>t.stage===i+1).length},${upgraded.filter(t=>t.stage===i+1).length*12},PLANNED_OR_EXTERNAL`).join('\n')+'\n');
write('five-stage-test-matrix.csv','test_id,stage_id,type,expected,evidence\n'+stageInfo.flatMap((s,i)=>Array.from({length:12},(_,j)=>`TEST-${String(i*12+j+1).padStart(3,'0')},${s.id},unit/integration/negative,explicit-state-and-data-preserved,not-run-external`)).join('\n')+'\n');
write('five-stage-risk-and-rollback-register.md',header+`| 위험 | 단계 | 차단 | 되돌리기 |\n|---|---|---|---|\n| DNS/Pages 대상 미확정 | 1 | 외부 권한 | 외부 변경 없음 |\n| OAuth/D1/키 미등록 | 2 | 계정·비밀값 | 로컬 계약 유지 |\n| 자료 손실·중복 | 3 | fixture/복구 | 스냅샷·버전 충돌 |\n| 접근성·성능 미검증 | 4 | 사람/기기 | 기능 플래그 off |\n| 공개·운영·법률 미승인 | 5 | 외부 증거 | 출시 보류·이전판 유지 |\n`);
write('five-stage-low-skill-ai-handbook.md',header+`## 저숙련 AI 실행 규칙\n\n1. 먼저 \`npm.cmd run handoff:check\`를 실행한다.\n2. 해당 stage README와 task card를 읽는다.\n3. 실제 파일·기호를 확인하기 전 코드를 만들지 않는다.\n4. 한 미세 단계 후 가장 작은 검사 하나를 실행한다.\n5. 실패하면 원문·종료코드·원인을 기록하고 같은 명령을 세 번 반복하지 않는다.\n6. 외부 차단은 WAITING_EXTERNAL로 남기고 독립 카드를 계속한다.\n7. 계획·자동검사·실기기·사람·운영 증거를 서로 바꾸어 표현하지 않는다.\n`);
write('five-stage-plan-quality-audit.md',header+`- 정확히 5단계 고정 ID: PASS\n- 단계별 24개 절: 120/120 PASS\n- 작업카드 96필드: ${upgraded.length}개 모두 PASS\n- 작업별 미세 단계: ${upgraded.length*12}개 계획\n- 작업별 고유 시험: ${upgraded.length*12}개 계획\n- X10 최소치: PARTIAL (후보 10/800, 지표 160/1,600, 경계사례 20/10,000)\n- 실제 구현·기기·사람·운영 증거: 0건\n- 최종 품질: PARTIAL_EVIDENCE; COMPLETE 아님\n`);
fs.mkdirSync(path.join(root,'five-stage-handoff-packets'),{recursive:true});
for(let i=0;i<5;i++)write(path.join('five-stage-handoff-packets',`stage-0${i+1}.md`),header+`## ${stageInfo[i].id} 인계 패킷\n\n- 입력: stage-0${i+1}/README.md와 해당 작업카드\n- 첫 행동: \`npm.cmd run handoff:check\`\n- 성공: 단계 증거 연결·자동검사 통과\n- 차단: 외부 계정/기기/사람 검증\n- 다음: ${i<4?stageInfo[i+1].id:'운영 관찰'}\n`);
write('run-manifest.json',JSON.stringify({schema_version:'world-top10-v3.3',run_id:runId,generated_at_utc:generatedAt,project_fingerprint:fingerprint,artifact_type:'run-manifest',source_artifact_ids:['SRC-013','SRC-014','SRC-015','SRC-016'],records:[],counts:{required_v32_artifacts:51,additional_v33_artifacts:10,stage_directories:5,recursive_files:96},unknowns:['Cloudflare DNS/Pages target','Google OAuth production project/client','D1/key production migration','real Android','human/legal/accessibility/ads evidence'],warnings,selected_mode:'END_TO_END',fixed_stage_ids:stageInfo.map(x=>x.id),gates:{G0:'PASS',G1:'PASS',G2:'PARTIAL',G3:'PARTIAL',G4:'PARTIAL',G5:'PARTIAL',G6:'PARTIAL',G7:'PARTIAL',G8:'PARTIAL'},overall_status:'PARTIAL_EVIDENCE',x10_one_shot:true,x10_status:'X10_PARTIAL_SCOPE',writes:{product_code:0,git:0,external_services:0}},null,2)+'\n');
write('INDEX.md',header+`## v3.3 핵심 산출물\n\n- [실행 장부](./run-manifest.json)\n- [5단계 색인](./FIVE_STAGE_DEVELOPMENT_INDEX.md)\n- [저숙련 AI 무해석 상세개발계획](./five-stage-detailed-development-plan.md)\n- [통합 5단계 개발계획](./integrated-development-plan-5-stages.md)\n- [96필드 작업카드](./development-task-cards.json)\n- [세부 장부](./five-stage-detail-ledger.json)\n- [품질 감사](./five-stage-plan-quality-audit.md)\n- [기존 v3.2 통합 기획](./integrated-product-plan-vNEXT.md)\n- [Top10 비교](./world-top10-selection.md)\n- [격차 우선순위](./gap-priority-report.md)\n\n## 판정\n\n- G0~G1 PASS, G2~G8 PARTIAL/BLOCKED_EXTERNAL\n- X10_PARTIAL_SCOPE\n- 실제 배포·OAuth·D1·기기·사람 검증 0건\n- 제품 코드·Git·외부 서비스 변경 0건\n`);
write('FIVE_STAGE_DEVELOPMENT_INDEX.md',header+stageInfo.map((s,i)=>`- [${s.id}](./stage-0${i+1}/README.md) — ${s.goal}`).join('\n')+'\n\n- [단계 의존 그래프](./five-stage-dependency-graph.md)\n- [시험 매트릭스](./five-stage-test-matrix.csv)\n- [위험·롤백](./five-stage-risk-and-rollback-register.md)\n- [저숙련 AI 핸드북](./five-stage-low-skill-ai-handbook.md)\n- [인계 패킷](./five-stage-handoff-packets/)\n');
console.log(JSON.stringify({runId,root,files:fs.readdirSync(root).length,stageIds:stageInfo.map(x=>x.id),tasks:upgraded.length,fields:96,status:'PARTIAL_EVIDENCE',x10:'X10_PARTIAL_SCOPE'},null,2));
