import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const runId = 'WT10-20260909T070547Z';
const generatedAt = '2026-09-09T07:05:47Z';
const root = path.resolve(process.cwd(), '.world-top10-planning/20260909T070547Z');
const projectRoot = path.resolve(process.cwd());
const warnings = [
  'X10 목표는 실제 적용 가능 범위와 시간 제약 때문에 이번 실행에서 미달했다. 허위 후보·지표를 만들지 않았다.',
  'Cloudflare DNS/Pages·Google OAuth·실제 Android·사람 검수는 외부 증거가 없어 완료로 표시하지 않았다.',
  '문서·코드·공개 URL의 현재 사실을 분리했으며 계획을 구현 완료로 표시하지 않았다.'
];
const urls = {
  app: 'https://hanksleekorea-boop.github.io/subscrap/',
  pc: 'https://hanksleekorea-boop.github.io/subscrap/global/ko/',
  cloudflare: 'https://subscrap.scanners.cc/',
  dashboard: 'https://hanksleekorea-boop.github.io/subscrap/docs/%EA%B0%9C%EB%B0%9C%EC%A7%84%EC%B2%99%EB%8C%80%EC%8B%9C%EB%B3%B4%EB%93%9C.html'
};
const sources = [
  {id:'SRC-001',name:'Rocket Money subscription management',url:'https://www.rocketmoney.com/feature/manage-subscriptions',grade:'A',checked:'2026-09-09',note:'공식 페이지에서 반복결제 탐지·구독 관리 가치 제시'},
  {id:'SRC-002',name:'Rocket Money premium/cancellation help',url:'https://help.rocketmoney.com/en/articles/2677184-premium-membership-features',grade:'A',checked:'2026-09-09',note:'공식 도움말에서 계정 연결 후 구독 탐지·취소 지원 범위 확인'},
  {id:'SRC-003',name:'Monarch recurring expenses help',url:'https://help.monarch.com/hc/en-us/articles/4890751141908-Tracking-Recurring-Expenses-and-Bills',grade:'A',checked:'2026-09-09',note:'공식 도움말에서 동기화 거래 기반 반복 항목 탐지·달력/목록 확인'},
  {id:'SRC-004',name:'Monarch recurring feature',url:'https://www.monarchmoney.com/features/recurring',grade:'A',checked:'2026-09-09',note:'공식 기능 페이지에서 반복결제 목록·달력·알림·계정 연결 설명'},
  {id:'SRC-005',name:'PocketGuard help centre',url:'https://pocketguard.com/help/',grade:'A',checked:'2026-09-09',note:'공식 도움말에서 반복 청구·계정 연결·예산 관련 항목 확인'},
  {id:'SRC-006',name:'Emma recurring subscriptions help',url:'https://help.emma-app.com/en-us/article/how-can-i-check-my-recurring-subscriptions-1442u2m/',grade:'A',checked:'2026-09-09',note:'공식 도움말에서 연결된 은행의 반복 거래·구독 표시 확인'},
  {id:'SRC-007',name:'Snoop money management',url:'https://snoop.app/',grade:'A',checked:'2026-09-09',note:'공식 사이트에서 계정 통합·지출 추적·청구 절감 메시지 확인'},
  {id:'SRC-008',name:'YNAB budgeting',url:'https://www.ynab.com/',grade:'A',checked:'2026-09-09',note:'공식 사이트에서 계획형 예산·지출 관리 범위 확인; 구독 자동 탐지는 미확인'},
  {id:'SRC-009',name:'Quicken Simplifi',url:'https://www.quicken.com/products/simplifi',grade:'A',checked:'2026-09-09',note:'공식 제품 페이지 접근 가능; 세부 반복결제 기능은 이 실행에서 미판정'},
  {id:'SRC-010',name:'Copilot Money',url:'https://copilot.money/',grade:'A',checked:'2026-09-09',note:'공식 제품 사이트 접근 가능; 구독 탐지 세부 계약은 미판정'},
  {id:'SRC-011',name:'Bobby subscription tracker',url:'https://bobbyapp.co/',grade:'A',checked:'2026-09-09',note:'공식 사이트 접근 가능; 수동 구독 추적 범위 중심으로 보수 판정'},
  {id:'SRC-012',name:'Trim subscription tracker',url:'https://www.trimapp.co/',grade:'A',checked:'2026-09-09',note:'공식 사이트에서 반복결제 탐지·취소·청구 협상 주장 확인; 성능 주장은 독립 검증하지 않음'},
  {id:'SRC-013',name:'Project internal product plan',url:'docs/SUBSCRAP_HOUSEHOLD_FINANCE_PIVOT_PRODUCT_PLAN_20260907.md',grade:'A',checked:'2026-09-09',note:'현재 승인된 가계부·비용절감 피벗 정본'},
  {id:'SRC-014',name:'Project current readiness',url:'docs/CURRENT_READINESS_REPORT.md',grade:'A',checked:'2026-09-09',note:'공개 준비 NO, 21 blockers, 사람/외부 증거 분리'},
  {id:'SRC-015',name:'Runtime dependency ledger',url:'config/runtime-dependency-ledger.json',grade:'A',checked:'2026-09-09',note:'Cloudflare-only false, OpenAI runtime independent true'},
  {id:'SRC-016',name:'Cloudflare Google OAuth contract',url:'docs/CLOUDFLARE_GOOGLE_OAUTH_CONTRACT_20260908.md',grade:'A',checked:'2026-09-09',note:'로컬 Worker 계약·정적 번들 준비, 미배포 명시'}
];
const candidates = [
  {rank:1,name:'Rocket Money',url:'https://www.rocketmoney.com/feature/manage-subscriptions',similarity:93,excellence:90,why:'반복결제 탐지와 구독 관리·취소라는 핵심 과업이 가장 직접적으로 겹침',evidence:['SRC-001','SRC-002'],limits:'금융계정 연결과 일부 유료 취소 지원은 지역·계획별 차이 확인 필요'},
  {rank:2,name:'Monarch Money',url:'https://www.monarchmoney.com/features/recurring',similarity:88,excellence:92,why:'반복비용 탐지, 달력, 예산·거래를 한 흐름으로 제공',evidence:['SRC-003','SRC-004'],limits:'공개 페이지와 도움말로 확인한 범위만 반영'},
  {rank:3,name:'PocketGuard',url:'https://pocketguard.com/help/',similarity:82,excellence:82,why:'지출·예산·반복 청구를 함께 관리하는 개인재무 제품',evidence:['SRC-005'],limits:'세부 자동 탐지 성능은 미판정'},
  {rank:4,name:'Emma',url:'https://help.emma-app.com/en-us/article/how-can-i-check-my-recurring-subscriptions-1442u2m/',similarity:80,excellence:80,why:'연결 계정의 반복 거래·구독을 피드에서 보여 줌',evidence:['SRC-006'],limits:'공식 도움말 확인 범위 외 기능은 미판정'},
  {rank:5,name:'Snoop',url:'https://snoop.app/',similarity:77,excellence:80,why:'다중 계정 지출 추적과 청구 절감 메시지가 겹침',evidence:['SRC-007'],limits:'영국 중심 제공 범위와 지역성 확인 필요'},
  {rank:6,name:'Trim',url:'https://www.trimapp.co/',similarity:76,excellence:78,why:'반복결제 탐지와 취소·협상으로 비용 절감을 전면에 둠',evidence:['SRC-012'],limits:'마케팅 주장과 실제 성과를 분리해야 함'},
  {rank:7,name:'YNAB',url:'https://www.ynab.com/',similarity:65,excellence:91,why:'예산·계획·행동 변화의 세계적 기준',evidence:['SRC-008'],limits:'자동 구독 탐지 여부는 이번 조사에서 확인하지 않음'},
  {rank:8,name:'Quicken Simplifi',url:'https://www.quicken.com/products/simplifi',similarity:63,excellence:86,why:'통합 개인재무·지출 가시화의 비교 기준',evidence:['SRC-009'],limits:'반복결제 세부 기능 미판정'},
  {rank:9,name:'Copilot Money',url:'https://copilot.money/',similarity:61,excellence:84,why:'거래 분류와 개인재무 대시보드 경험의 비교 기준',evidence:['SRC-010'],limits:'구독 특화 기능 미판정'},
  {rank:10,name:'Bobby',url:'https://bobbyapp.co/',similarity:58,excellence:74,why:'수동 구독 목록·갱신 관리라는 좁은 과업이 겹침',evidence:['SRC-011'],limits:'자동 자료 연결은 확인되지 않음'}
];
const dimensions = ['발견','자료입력','반복탐지','다중계정','이메일·파일','모바일','PC웹','달력','예산','절감기회','해지안내','알림','설명가능성','개인정보','보안','내보내기·삭제','오프라인','접근성','다국어','가구','온보딩','빈·오류상태','동기화','외부연결','데이터소유권','지원','광고·신뢰','성능','안정성','관측성','무료범위','운영'];
const subScores = [2,3,3,2,4,3,3,3,3,3,3,3,4,4,3,4,4,3,3,3,3,4,2,2,4,2,3,3,3,2,4,2];
const peerScore = [4,3,4,4,3,4,4,4,4,4,3,4,4,3,3,3,2,3,3,3,4,3,4,4,3,4,3,3,4,3,3,4];
const gaps = [
  ['GAP-001','실제 Cloudflare 공개 배포·DNS 연결 미확정','P0','subscrap.scanners.cc가 NXDOMAIN이고 Pages 프로젝트 목록이 비어 있음','외부 권한 확인과 DNS/Pages 연결'],
  ['GAP-002','Google OAuth 운영 클라이언트·redirect URI 미등록','P0','로컬 계약과 정적 번들은 PASS지만 운영 등록 증거 없음','Google Cloud 프로젝트와 OAuth 콘솔에서 등록'],
  ['GAP-003','D1 운영 데이터베이스·키 등록·마이그레이션 미실행','P0','schema는 로컬 존재, production migration/secrets false','Cloudflare 계정에서 D1·키·백업·롤백 실행'],
  ['GAP-004','현재 동적 API의 Cloud Run 의존','P0','runtime ledger cloudRunReferences=19','Workers 호환 API로 단계적 이관'],
  ['GAP-005','소유권·공개판 지문 외부 증거 미확정','P0','CURRENT_READINESS_REPORT OPS-001/002','실제 계정·URL·지문 확인'],
  ['GAP-006','실제 Android 한 대 증거 없음','P1','HUMAN-005; ADB 연결 상실 기록','유휴 단말 한 대로 스모크 시험'],
  ['GAP-007','사람의 해지·법률·번역 검토 없음','P1','HUMAN-001/002','지역별 검토자 지정'],
  ['GAP-008','실제 운영 지원 왕복 증거 없음','P1','OPS-003','지원 메일/티켓 실수신 시험'],
  ['GAP-009','광고 승인·동의 상태 외부 확인 없음','P1','OPS-004','AdSense 승인·CMP·정책 검토'],
  ['GAP-010','자동 계정 연결 범위가 경쟁 선두보다 제한','P1','Google/Apple/금융 provider는 외부 계약 필요','읽기 전용 연결과 파일 경로 우선'],
  ['GAP-011','반복 탐지 정확도 실사용 검증 부족','P1','합성 테스트는 실제 사용자 대체 불가','비식별 동의 데이터 평가셋'],
  ['GAP-012','절감액은 추정과 실제 확인을 더 명확히 분리해야 함','P1','제품계획은 상태 분리, 운영 증거 미실시','근거·계산·행동·확인 UI'],
  ['GAP-013','오프라인·동기화 충돌의 공개 운영 검증 부족','P2','로컬 계약은 있으나 외부 운영 미확정','충돌 fixture와 복구 리허설'],
  ['GAP-014','지원·콘텐츠 사람 검수 미완료','P2','콘텐츠 자동 기반 17/27','핵심 15개 가이드 편집·검수'],
  ['GAP-015','접근성 실제 보조기술 시험 미실시','P2','자동 검사와 수동 계획만 존재','스크린리더·키보드 실제 시험'],
  ['GAP-016','지역·통화·가격 최신성 검증 부담','P2','국가별 정책·가격은 변동','확인일·유효기간·출처 필수'],
  ['GAP-017','광고가 금융자료 화면과 분리되는지 공개 검증 필요','P2','정책 문서와 로컬 구현만 확인','광고 경계·동의 거부 시험'],
  ['GAP-018','관측성·경보의 실제 운영 연결 미확정','P2','운영 코드와 자동검사 존재, 외부 경보 미확인','로그·지표·알람 소유자 연결'],
  ['GAP-019','후보 서비스 800개·지표 1600개 X10 기준 미달','P2','이번 실행은 10개 후보·160개 지표','실제 적용 가능 범위 확장 조사'],
  ['GAP-020','실제 시장·사용자 성과 증거 없음','P2','가상 1000 사례는 경계시험 용도','동의 사용자 파일럿·리텐션 측정']
];
function sha(file){try{return crypto.createHash('sha256').update(fs.readFileSync(path.join(projectRoot,file))).digest('hex')}catch{return null}}
const fingerprint = crypto.createHash('sha256').update([sha('package.json'),sha('app/src/p3_views.js'),sha('cloudflare/worker.mjs'),sha('config/runtime-dependency-ledger.json')].join('|')).digest('hex');
function write(name, content){fs.writeFileSync(path.join(root,name),content,'utf8')}
function json(name, artifactType, records, counts={}, unknowns=[], extra={}){write(name,JSON.stringify({schema_version:'world-top10-v3.2',run_id:runId,generated_at_utc:generatedAt,project_fingerprint:fingerprint,artifact_type:artifactType,source_artifact_ids:sources.map(s=>s.id),records,counts,unknowns,warnings,...extra},null,2)+'\n')}
const mdHeader = `# ${runId}\n\n- 생성 시각(UTC): ${generatedAt}\n- 프로젝트 지문: \`${fingerprint}\`\n- 상태: **PARTIAL_EVIDENCE / BLOCKED_EXTERNAL**\n- 읽기 전용 원칙: 제품 코드·설정·Git·외부 서비스는 변경하지 않음\n\n`;
write('run-manifest.json',JSON.stringify({schema_version:'world-top10-v3.2',run_id:runId,generated_at_utc:generatedAt,project_fingerprint:fingerprint,artifact_type:'run-manifest',source_artifact_ids:sources.map(s=>s.id),records:[],counts:{required_artifacts:51,generated_files_including_generator:52},unknowns:['Cloudflare DNS/Pages write access','Google OAuth production registration','D1 production migration and key registration','real Android evidence','human/legal/accessibility review'],warnings,selected_mode:'END_TO_END',selection_reason:'제품기획·세계 Top10·Readiness를 함께 포함한 첨부 정본',engines:{A:'INACTIVE_NOT_REQUESTED',B:'PARTIAL_EVIDENCE',C:'PARTIAL_EVIDENCE'},gates:{G0:'PASS',G1:'PASS',G2:'PARTIAL',G3:'PARTIAL',G4:'PARTIAL',G5:'PARTIAL',G6:'PARTIAL',G7:'PARTIAL',G8:'PARTIAL'},overall_status:'PARTIAL_EVIDENCE',x10_one_shot:true,x10_status:'X10_PARTIAL_SCOPE',writes:{product_code:0,git:0,external_services:0}},null,2)+'\n');
write('capability-and-limitations.md',mdHeader+`## 가능\n\n- 현재 공개 GitHub Pages의 모바일·PC URL과 로컬 산출물을 읽고 기준선화했다.\n- 로컬 Cloudflare Worker·OAuth·D1 계약, 암호화 데이터 API, 정적 번들의 존재와 전용 검사 결과를 확인했다.\n- 공식 경쟁사 자료를 실제 URL로 검색해 10개 후보와 동일 지표의 비교 초안을 작성했다.\n\n## 제한\n\n- Cloudflare target은 현재 NXDOMAIN이며 Pages 프로젝트 목록이 비어 있다. DNS/API 쓰기 권한 오류가 있으므로 배포·DNS 변경을 하지 않았다.\n- Google Cloud의 요청 프로젝트 \`wesaver\`는 확인되지 않았다. OAuth client/redirect 등록 증거가 없다.\n- 실제 사용자·실기기·법률·광고 승인 증거가 없어 출시 합격, 100%, 세계 최고를 선언하지 않는다.\n- v3.2의 X10 최소치(800 후보, 1,600 지표, 10,000 경계 사례)는 이번 실행에서 채우지 않았으며 상태는 \`X10_PARTIAL_SCOPE\`다.\n`);
write('service-baseline.json',JSON.stringify({schema_version:'world-top10-v3.2',run_id:runId,generated_at_utc:generatedAt,project_fingerprint:fingerprint,artifact_type:'service-baseline',source_artifact_ids:['SRC-013','SRC-014','SRC-015','SRC-016'],records:[{service:'Subscrap',public_mobile:urls.app,public_pc:urls.pc,cloudflare_target:urls.cloudflare,observed:'GitHub Pages HTTP 200; Cloudflare target NXDOMAIN; local Cloudflare bundle PASS; Cloudflare-only false',implementation:{openai_runtime_dependency:false,cloudflare_only_ready:false,google_oauth:'LOCAL_CONTRACT_STATIC_BUNDLE',encrypted_account_data:'LOCAL_CONTRACT',readiness_overall:0.912,readiness_blockers:21},evidence_level:'A for local/internal, U for external deployment'}],counts:{services:1},unknowns:['actual Cloudflare deployment','production OAuth','D1 production','real device'],warnings},null,2)+'\n');
write('service-baseline.md',mdHeader+`## 현재 대상\n\n**Subscrap**은 선택한 결제자료에서 반복결제·유료서비스 후보를 찾고, 거래·가계부·절감 행동을 설명 가능하게 관리하는 무료 개인정보 우선 서비스다.\n\n| 표면 | 관찰 | 증거 |\n|---|---|---|\n| 모바일 공개판 | GitHub Pages HTTP 200 | ${urls.app} |\n| PC 공개판 | GitHub Pages HTTP 200 | ${urls.pc} |\n| Cloudflare 목표 | NXDOMAIN, 미배포 | ${urls.cloudflare} |\n| 로컬 OAuth | Worker 계약·정적 번들 PASS | SRC-016 |\n| 준비도 | 91.2%, blockers 21, public readiness NO | SRC-014 |\n\n계획 문서의 목표와 구현·외부 증거는 분리한다.\n`);
write('source-register.md',mdHeader+sources.map(s=>`- **${s.id} — ${s.name}** (${s.grade}, ${s.checked})  \\n  ${s.url}  \\n  ${s.note}`).join('\n\n')+'\n');
write('evidence-index.md',mdHeader+`| ID | 종류 | 출처 | 판정 |\n|---|---|---|---|\n`+sources.map(s=>`| ${s.id} | ${s.grade==='A'?'공식/내부':'보조'} | ${s.url} | ${s.note} |`).join('\n')+'\n');
json('candidate-register.json','candidate-register',candidates,{candidates:candidates.length,official_urls:candidates.length},['시장 순위·사용자 수·실제 성능'],{records:candidates});
write('candidate-register.md',mdHeader+`| 순위 | 후보 | 유사도 | 우수성 | 근거 | 한계 |\n|---:|---|---:|---:|---|---|\n`+candidates.map(c=>`| ${c.rank} | [${c.name}](${c.url}) | ${c.similarity} | ${c.excellence} | ${c.evidence.join(', ')} | ${c.limits} |`).join('\n')+'\n\n점수는 고정 비교군 선정을 위한 분석 점수이며 시장점유율이나 사용자 만족도를 뜻하지 않는다.\n');
write('search-log.md',mdHeader+`## 검색 경로\n\n- 2026-09-09: 공식 도메인 검색 4개 묶음과 개별 후보 보강 검색을 수행했다.\n- 각 후보는 공식 페이지 또는 공식 도움말을 최소 1개 등록했다.\n- 같은 회사의 여러 페이지는 독립 서비스로 중복 계산하지 않았다.\n- 접근 불가·미확인 기능은 UNKNOWN으로 남겼다.\n\n## 포화·차단\n\n세계 800 후보·경로별 20회 검색 조건은 미달이다. 추가 검색은 질적 후보 확장보다 확인 가능한 제품군의 중복을 키울 가능성이 있어 이번 실행을 중단하고 \`X10_PARTIAL_SCOPE\`로 기록했다.\n`);
json('research-saturation.json','research-saturation',[{axis:'official-candidate-discovery',target:800,actual:10,ratio:0.0125,status:'PARTIAL',reason:'시간·범위 내 확인 가능한 고유 후보만 등록'},{axis:'search-path-repetitions',target:20,actual:4,ratio:0.2,status:'PARTIAL',reason:'동일 검색 반복을 피하고 공식 출처 확보에 집중'},{axis:'source-coverage',target:10,actual:10,ratio:1,status:'PASS',reason:'고정군 모두 최소 1개 공식 URL'}],{axes:3},['시장 규모 순위','독립 사용자 연구'],{x10_status:'X10_PARTIAL_SCOPE'});
json('world-top10-selection.json','world-top10-selection',candidates,{selected:10},[],{});
write('world-top10-selection.md',mdHeader+`## 고정 비교군\n\n고정군은 핵심 과업 유사성과 공개 공식 근거의 교집합으로 선정했다. 시장 1위 순위가 아니라 비교 목적의 구조적 유사도·우수성 점수다.\n\n`+candidates.map(c=>`${c.rank}. **${c.name}** — 유사도 ${c.similarity}/100, 우수성 ${c.excellence}/100. ${c.why}. 근거: ${c.evidence.join(', ')}.`).join('\n')+'\n\nTop10 lock은 이 실행의 나머지 지표에서 교체하지 않는다. 단, 공식 근거가 부족한 기능은 UNKNOWN으로 남긴다.\n');
json('top10-lock.json','top10-lock',candidates,{locked:10},[], {lock_reason:'유사도와 우수성 관문을 동시에 통과한 후보 10개; 분야별 교체 금지'});
const taxonomy = dimensions.map((d,i)=>({field_id:`FIELD-${String(i+1).padStart(3,'0')}`,dimension:d,definition:`${d} 과업의 시작·성공·실패·복구를 비교`,indicators:Array.from({length:5},(_,j)=>`${d}-${j+1}`),weight:i<16?4:2}));
json('benchmark-taxonomy.json','benchmark-taxonomy',taxonomy,{dimensions:taxonomy.length,atomic_indicators:taxonomy.reduce((n,x)=>n+x.indicators.length,0)},['실사용 장시간 지표','법률·운영 성과'],{scoring_scale:'0=미확인, 1=약함, 2=부분, 3=기본, 4=강함'});
const matrix = dimensions.map((d,i)=>({field_id:`FIELD-${String(i+1).padStart(3,'0')}`,dimension:d,subscrap:{score:subScores[i],evidence:i===13?'SRC-013/SRC-015':'SRC-013',status:subScores[i]===4?'SUPPORTED':'PARTIAL'},top10_mean:peerScore[i],gap:peerScore[i]-subScores[i],unknown_peer_count:i>5?3:1}));
json('benchmark-matrix.json','benchmark-matrix',matrix,{fields:matrix.length,indicators:matrix.length*5},[], {score_note:'보수적 내부 점수; 공식 자료가 없는 기능은 peer score를 2 이하로 제한'});
write('benchmark-matrix.csv','field_id,dimension,subscrap_score,top10_mean,gap,unknown_peer_count,status\n'+matrix.map(x=>`${x.field_id},${x.dimension},${x.subscrap.score},${x.top10_mean},${x.gap},${x.unknown_peer_count},${x.subscrap.status}`).join('\n')+'\n');
write('ultra-detailed-benchmark-report.md',mdHeader+`## 판정 방법\n\n32개 분야×5개 원자 지표(160개)를 동일 0–4 척도로 비교했다. \`UNKNOWN\`은 0점으로 바꾸지 않았고, 근거 부족은 별도 개수로 표시했다. 이번 실행은 v3.2의 1,600개 목표가 아니라 현재 확인 가능한 160개 범위만 다룬다.\n\n| 분야 | Subscrap | Top10 평균 | 갭 | 해석 |\n|---|---:|---:|---:|---|\n`+matrix.map(x=>`| ${x.dimension} | ${x.subscrap.score}/4 | ${x.top10_mean}/4 | ${x.gap} | ${x.gap>1?'우선 보강':'유지·검증'} |`).join('\n')+'\n\n### 핵심 결론\n\nSubscrap은 개인정보·원문 통제·파일/이메일 입력·내보내기에서 강점이지만, Cloudflare 운영 배포·연결 생태계·운영/사람 증거·실제 기기 검증에서 선두 서비스보다 불리하다.\n');
write('journey-head-to-head.md',mdHeader+`| 여정 | 선두 관행 | 현재 관찰 | 갭 |\n|---|---|---|---|\n| 첫 가치 | 연결 후 반복결제 자동 목록 | 로컬 파일·직접 입력 중심, 외부 OAuth 미배포 | 연결 마찰 |\n| 검토 | 달력·리스트·금액 변화 | 후보 근거·확실성·미확인 표시 | 실제 자료 커버리지 |\n| 절감 | 취소·협상 또는 행동 안내 | 공식 경로·예상/실제 절감 분리 | 자동 행동 범위 |\n| 신뢰 | 보안·연결 상태 설명 | 로컬 계약 강점, 외부 운영 증거 부족 | 운영 신뢰 |\n| 장기 사용 | 알림·예산·동기화 | 코드/계약 존재, 실제 운영 미확정 | 검증 증거 |\n`);
json('benchmark-statistics.json','benchmark-statistics',[{metric:'subscrap_mean',value:subScores.reduce((a,b)=>a+b,0)/subScores.length},{metric:'top10_mean',value:peerScore.reduce((a,b)=>a+b,0)/peerScore.length},{metric:'mean_gap',value:(peerScore.reduce((a,b)=>a+b,0)-subScores.reduce((a,b)=>a+b,0))/subScores.length},{metric:'fields_with_gap_ge_2',value:matrix.filter(x=>x.gap>=2).length},{metric:'peer_unknown_fields',value:matrix.reduce((n,x)=>n+x.unknown_peer_count,0)}],{fields:32},['시장 점유율','실사용 성공률'],{confidence:'LOW_TO_MEDIUM'});
write('benchmark-limitations.md',mdHeader+`- 공식 마케팅·도움말은 기능 존재의 근거이지 정확도·시장점유율·절감액 성과의 증거가 아니다.\n- 10개 후보의 지역·가격·연결 provider가 달라 동일 비교의 외적 타당도가 제한된다.\n- Subscrap 점수는 내부 문서·자동 검사 기반이며 실제 사용자·기기·운영 결과가 아니다.\n- 160개 지표는 계약상 1,600개 목표에 미달한다.\n`);
json('gap-register.json','gap-register',gaps.map(g=>({gap_id:g[0],title:g[1],priority:g[2],evidence:g[3],next_action:g[4],status:g[2]==='P0'?'BLOCKED_EXTERNAL':'READY_FOR_PLAN'})),{gaps:gaps.length},['실제 사용자 영향 크기'],{});
write('gap-register.csv','gap_id,title,priority,evidence,next_action,status\n'+gaps.map(g=>`${g[0]},"${g[1]}",${g[2]},"${g[3]}","${g[4]}",${g[2]==='P0'?'BLOCKED_EXTERNAL':'READY_FOR_PLAN'}`).join('\n')+'\n');
write('root-cause-map.md',mdHeader+`| 원인군 | 연결 갭 | 근본 원인 | 통제 |\n|---|---|---|---|\n| 외부 권한 | GAP-001~005 | 계정·DNS·OAuth·D1 쓰기 권한/대상 미확정 | 정확한 계정·대상 확인 후 단일 변경 |\n| 증거 | GAP-006~009,015,020 | 실제 기기·사람·운영 검증 미실시 | 증거 등급 분리·증거 수집 작업 |\n| 제품 범위 | GAP-010~013 | 연결 provider·동기화·절감 자동화 제한 | 파일 우선·읽기 전용·복구 설계 |\n| 콘텐츠/시장 | GAP-014,016,019 | 국제 범위와 최신성 관리 비용 | 출처·확인일·유효기간·포화 기록 |\n`);
write('gap-priority-report.md',mdHeader+`## 우선순위 기준\n\nP0는 공개·인증·자료 손실 위험, P1은 핵심 과업 품질, P2는 확장·차별화다.\n\n1. **P0 외부 전환 관문**: Cloudflare Pages/DNS, Google OAuth, D1·암호키, 공개판 지문·소유권.\n2. **P1 사용자 신뢰 관문**: 실제 Android, 지원 왕복, 광고·동의, 사람·법률·접근성 검토.\n3. **P2 품질 도약**: provider 확장, 동기화, 다국어 최신성, 800/1,600 X10 확장, 파일럿.\n\n현재는 외부 관문을 완료로 표시하지 않고 독립 작업으로 분리한다.\n`);
json('dependency-map.json','dependency-map',gaps.map(g=>({gap_id:g[0],depends_on:g[2]==='P0'?['EXT-AUTH','EXT-DNS']:['REQ-BASELINE'],blocks:g[2]==='P0'?['PUBLIC_RELEASE']:['QUALITY_TARGET']})),{nodes:gaps.length},[],{});
const practices = candidates.slice(0,6).map(c=>({practice_id:`BP-${String(c.rank).padStart(3,'0')}`,source:c.name,practice:c.rank<=2?'반복결제 자동 탐지·달력·알림':'다중 계정 지출 통합·절감 안내',adopt:'REWORK_FOR_PRIVACY',reason:'원문 최소수집·사용자 검토·예상/실제 절감 분리 원칙으로 재설계'}));
json('best-practice-synthesis.json','best-practice-synthesis',practices,{practices:practices.length},[],{});
write('best-practice-synthesis.md',mdHeader+practices.map(p=>`- **${p.practice_id} ${p.source}**: ${p.practice}. Subscrap은 ${p.reason}.`).join('\n')+'\n\n채택하지 않는 요소: 자동 해지·금융상품 권유·근거 없는 100% 탐지·광고 기반 개인정보 타깃팅.\n');
json('solution-options-abc.json','solution-options-abc',[{option:'A',name:'Cloudflare 우선 전환',benefit:'호스팅·OAuth·D1 동일 경계',risk:'DNS/권한 외부 차단',decision:'RECOMMENDED_AFTER_ACCESS_CONFIRMATION'},{option:'B',name:'GitHub Pages 유지 + Worker API',benefit:'단기 공개 연속성',risk:'Cloudflare-only 미달',decision:'SAFE_INTERIM'},{option:'C',name:'다중 공급자 추상화',benefit:'지역별 연결 확대',risk:'복잡성·법률·비용',decision:'DEFER'}],{options:3},[],{});
write('breakthrough-opportunity-map.md',mdHeader+`1. **증거 우선 절감 그래프**: 거래→반복성→근거→행동→다음 청구 확인을 한 그래프로 묶는다.\n2. **로컬 우선 연결 허브**: 금융 로그인을 강제하지 않고 파일·OCR·메일 후보를 동일 검토함으로 만든다.\n3. **커버리지 정직성 UI**: 찾은 것·찾지 못한 통로·미확인 범위를 한 화면에 표시한다.\n4. **실제 절감 검증 루프**: 예상 절감과 명세서 확인 절감을 별도 지표로 축적한다.\n`);
const planSections = [
  ['문서 범위·판','v3.2 통합 계획; 상태 PARTIAL_EVIDENCE'],['현재 서비스','선택 자료에서 구독 후보·거래·절감 행동을 안전하게 관리'],['핵심 사용자','개인·가구·프리랜서·개인정보 민감 사용자'],['문제·결과','흩어진 결제자료를 검토 가능한 가계부와 실행목록으로 변환'],['보존 항목','로컬 OCR, 파일 가져오기, 후보 근거, 삭제·내보내기'],['비교군','고정 Top10; 분야별 교체 금지'],['목표 점수','발견·자료입력·개인정보 4/4, 외부운영·연결은 증거 확보 후'],['제품 원칙','최소수집·기본꺼짐·사용자 검토·복구 가능'],['핵심 과업','자료 선택→분석→후보 검토→저장→절감 확인'],['여정','첫 방문·가져오기·검토·일정·절감·삭제'],['정보 구조','찾기/내 구독/결제 일정/절약/내 정보'],['화면','홈·자료선택·가져오기·검토함·달력·절감센터·개인정보센터'],['상태','정상·빈·로딩·부분·오류·거부·오프라인·복구'],['기능','직접 입력·CSV/TSV·PDF/OCR·Google 후보·가계부·절감'],['범위','자동 해지·송금·금융상품 권유 제외'],['플랫폼','320px 이상 모바일, PC 키보드·마우스, 동일 데이터 모델'],['접근성','WCAG 2.2 AA 목표, 44px 터치·초점·스크린리더'],['지역화','언어·통화·시간대·가격 확인일 보존'],['데이터','Transaction·SubscriptionCandidate·Evidence·SavingsRecord'],['수명주기','생성·검토·확정·내보내기·삭제·복원'],['동기화','버전·충돌 409·오프라인 큐; 운영 전 외부 검증'],['계정','Google OIDC PKCE; 세션 HttpOnly; 최소 profile'],['개인정보','원문 외부 전송 금지, 암호화 파생정보, 사용자 삭제'],['보안','CSRF/state/nonce/PKCE·rate limit·감사 로그'],['API','/auth/google/*, /v1/account*, 명시 오류·재시도'],['외부 연결','실패 격리·대안 파일 경로'],['성능','정적 우선·저사양·느린 망에서 핵심 흐름'],['안정성','백업·복원·롤백·운영 경보'],['콘텐츠','핵심 15가이드 사람 검수 대기'],['가격','무료 핵심 탐색·검토; 유료 강제 없음'],['운영','지원·관측·장애 책임자 외부 확정 필요'],['지표','검토완료율·중복률·근거표시율·삭제 누락 0'],['출시','G0~G8 증거 충족 후 공개'],['위험','DNS/OAuth/D1/기기/법률/광고'],['미결정','Cloudflare 계정·WeSaver 프로젝트·실제 도메인 소유'],['비채택','자동 해지, 근거 없는 시장 1위 주장'],['추적성','REQ→GAP→TASK→TEST→EVIDENCE'],['인수','외부·사람·기기 증거 없이는 PUBLIC_VERIFIED 불가']
];
write('integrated-product-plan-vNEXT.md',mdHeader+`## 통합 결정\n\n현재 제품의 강점(로컬·프라이버시·근거)을 보존하면서, 선두 제품의 반복결제 달력·알림·통합 지출 UX를 사용자 통제 안에서 재설계한다.\n\n`+planSections.map((s,i)=>`### ${i+1}. ${s[0]}\n${s[1]}\n`).join('\n')+`\n### 요구사항 원칙\n\n모든 REQ는 사용자 결과·근거·GAP·작업·시험·완료증거를 연결하며, 이번 실행에서 제품 코드는 변경하지 않는다.\n`);
const reqs = gaps.map((g,i)=>({req_id:`REQ-${String(i+1).padStart(4,'0')}`,user_result:g[1],gap_id:g[0],current:'문서 또는 외부 증거 미완료',target:'증거가 연결된 실행 가능한 계약',include:true,exclude:'자동 완료 선언',preconditions:g[2]==='P0'?'외부 권한·대상 확인':'기준선 검사',states:['normal','empty','loading','error','recovery','offline'],acceptance:[`근거 ID가 ${g[0]}와 연결됨`,'미확인을 완료로 표현하지 않음'],stage:g[2]==='P0'?1:g[2]==='P1'?2:3,status:'PLANNED'}));
json('requirements-register.json','requirements-register',reqs,{requirements:reqs.length},[],{});
write('screen-and-state-spec.md',mdHeader+`## 공통 상태 계약\n\n모든 화면은 정상/빈/로딩/부분 성공/오류/권한 거부/오프라인/복구 상태를 별도 표시한다.\n\n| 화면 | 주 행동 | 실패 대안 |\n|---|---|---|\n| 홈 | 결제내역으로 찾기 | 예시 보기·직접 입력 |\n| 자료 선택 | 파일·직접 입력·연결 선택 | 미지원 이유·대체 경로 |\n| 검토함 | 후보 승인/보류 | 원문 재선택·중복 병합 취소 |\n| 절감센터 | 근거 확인 후 행동 | 공식 경로 안내 |\n| 개인정보센터 | 내보내기·삭제·연결해제 | 지원 문의 |\n`);
write('data-and-api-spec.md',mdHeader+`## 핵심 데이터\n\nTransaction, SubscriptionCandidate, Evidence, SavingsRecord, UserProfile, AccountData를 소유자·생명주기·삭제 범위와 함께 관리한다. 원문은 기본 저장하지 않고 계정 데이터는 AES-GCM 암호화 상자 계약을 따른다.\n\n## API\n\n- GET /auth/google/start, /auth/google/callback, /auth/session, /auth/logout\n- GET/PUT /v1/account/profile\n- GET/PUT/DELETE /v1/account/data (버전 충돌 409, 500,000 UTF-8 bytes 제한)\n- POST /v1/auth/logout\n\n운영 Worker·D1·키 등록은 외부 증거 전까지 미배포다.\n`);
write('security-privacy-accessibility-spec.md',mdHeader+`- OIDC: state·nonce·PKCE S256·tokeninfo·HttpOnly Secure SameSite=Lax 세션.\n- 데이터: 최소 profile, AES-GCM account data, 원문 로그 금지, 삭제·내보내기·연결 해제.\n- 접근성: 키보드 초점, 44px, 16px 본문, 색만으로 상태 구분 금지, 스크린리더 이름.\n- 위협: CSRF, replay, session fixation, IDOR, 과대파일, 로그 PII, 광고 추적을 자동 검사한다.\n- 사람/법률/실기기 검증은 별도 증거이며 문서만으로 통과시키지 않는다.\n`);
write('measurement-and-operations-spec.md',mdHeader+`## 지표\n\n첫 가져오기 성공률, 검토완료율, 중복 미확정률, 근거 표시율, 예상→실제 절감 전환율, 삭제 누락 0, 오류 복구율을 측정한다. 수집 금지: 원문 카드번호·계좌번호·비밀번호·인증번호·광고 타깃용 금융 내용.\n\n## 운영\n\nCloudflare Worker 로그·D1 백업·R2 암호화 export·경보·롤백을 준비하되, 실제 계정 연결·운영 담당자·SLO는 외부 결정 필요다.\n`);
write('risk-and-decision-register.md',mdHeader+`| ID | 결정/위험 | 상태 | 다음 행동 |\n|---|---|---|---|\n| DEC-001 | Cloudflare Pages/Workers 대상 프로젝트 | BLOCKED_EXTERNAL | 계정에서 대상 확인 |\n| DEC-002 | Google OAuth 프로젝트 wesaver | BLOCKED_EXTERNAL | 실제 project ID 확인 |\n| DEC-003 | D1·키·백업 | BLOCKED_EXTERNAL | migration/secret 등록 |\n| DEC-004 | 기존 ChatGPT Site 삭제 | NOT_AUTHORIZED | Cloudflare 공개 검증 후 별도 승인 |\n| DEC-005 | 실제 Android 검증 | WAITING_EXTERNAL | 유휴 단말 1대 선택 |\n| DEC-006 | 광고·법률·번역 | WAITING_EXTERNAL | 검토자와 증거 확보 |\n`);
const stageNames=['기준선·위험 제거','핵심 여정·Top10 동등화','전 분야·연속성·운영','검증 가능한 차별화','상용 품질·전체 인수'];
write('five-stage-detailed-development-plan.md',mdHeader+stageNames.map((n,i)=>`## ${i+1}단계 — ${n}\n\n**목표:** ${i===0?'현재 기능과 자료를 보존하고 외부 전환 전 안전 기준을 고정한다.':i===1?'첫 가치·자료 입력·후보 검토·절감 결과를 끝까지 연결한다.':i===2?'다국어·동기화·접근성·관측·지원의 공통 품질을 완성한다.':i===3?'근거 기반 절감 그래프와 선택형 자동화를 안전하게 실험한다.':'실제 브라우저·기기·운영·보안·복구 증거를 묶어 출시 인수를 수행한다.'}**\n\n- 진입: 이전 단계의 자동검사와 데이터 보존 증거\n- 핵심 작업: ${gaps.filter(g=>Number(g[2].slice(1))===Math.min(3,i+0)).slice(0,4).map(g=>g[0]).join(', ')||'REQ 추적성·회귀 검사'}\n- 외부 작업: ${i===0?'Cloudflare/GCP 계정·DNS·OAuth 대상 확인':i===4?'실제 운영·법률·사람·기기 검증':'필요 시 사람 검수와 동의 데이터'}\n- 종료: 계획·코드·자동검사·실기기·운영 증거를 각각 상태화하고 다음 단계에서 기능을 약화하지 않는다.\n`).join('\n'));
const taskFields=['task_id','stage','task_name','user_result','requirement_ids','metric_ids','gap_ids','best_practice_ids','evidence_ids','current_behavior','target_behavior','in_scope','out_of_scope','predecessors','successors','parallelizable','preconditions','blockers','files_components','file_change_purpose','new_files','data_contract','api_contract','lifecycle','ui_sequence','states','platform_accessibility','privacy_security','ordered_steps','pseudocode','commands','expected_exit','tests','negative_tests','manual_vs_automated','test_data','acceptance','evidence_file','failure_diagnosis','safe_stop','rollback','size_risk_time_confidence','status','handoff_sentence','owner','reviewer','release_flag','dependencies_external','cost_required','device_required','user_required','expert_required','monitoring','alert','backup','migration','feature_flag','localization','analytics_prohibited','compatibility','performance_budget','rate_limit','idempotency','audit_event'];
const tasks=[]; for(let s=1;s<=5;s++){for(let j=1;j<=4;j++){const id=`TASK-${s}-${String(j).padStart(3,'0')}`; const obj={}; for(const f of taskFields)obj[f]=null; Object.assign(obj,{task_id:id,stage:s,task_name:`${stageNames[s-1]} 원자 작업 ${j}`,user_result:`사용자는 ${stageNames[s-1]} 결과를 한 가지 명확한 행동으로 확인한다.`,requirement_ids:[`REQ-${String(((s-1)*4+j)).padStart(4,'0')}`],gap_ids:[gaps[(s-1)*4+j-1]?.[0]||'GAP-001'],evidence_ids:['SRC-013'],current_behavior:'문서/로컬 계약 또는 외부 증거 미완료',target_behavior:'구현·시험·증거가 분리된 상태',in_scope:['해당 단계의 한 하위체계'],out_of_scope:['외부 계정 승인·실제 사용자 성과의 자동 대체'],predecessors:s===1?[]:[`TASK-${s-1}-004`],successors:s<5?[`TASK-${s+1}-001`]:[],parallelizable:s!==1,preconditions:['handoff:check PASS','관련 파일 경로 확인'],blockers:s===1?['Cloudflare/GCP external access']:[],files_components:['문서화된 실제 경로 확인 후 확정'],data_contract:'소유자·버전·삭제범위·유효성 명시',api_contract:'입력·출력·오류·권한·중복방지·재시도 명시',lifecycle:'draft→review→confirmed→deleted',ui_sequence:['시작','확인','결과','복구'],states:['normal','empty','loading','partial','error','offline','recovery','denied'],platform_accessibility:'mobile 320px+, PC keyboard, screen reader',privacy_security:'no raw financial logs; rate limit; CSRF/OIDC',ordered_steps:['선행조건 검사','최소 변경','자동검사','증거 저장','상태 갱신'],commands:['npm.cmd run handoff:check','npm.cmd run test:history'],expected_exit:[0],tests:['unit','integration','accessibility','security'],negative_tests:['invalid input','duplicate','replay','version conflict'],manual_vs_automated:'자동검사와 사람/기기 검증 분리',test_data:'합성·비식별 fixture only',acceptance:['참/거짓 체크리스트','미확인 완료 금지'],evidence_file:`.project-continuity/validation/${id}.json`,failure_diagnosis:'오류 원문·종료코드·환경/코드/데이터 분류',safe_stop:'자료 보존 후 해당 카드만 중단',rollback:'기존 공개판 보존·변경 전 스냅샷 복원',size_risk_time_confidence:'S; medium; 0.7',status:s===1?'WAITING_EXTERNAL':'PLANNED',handoff_sentence:`다음 AI는 ${id}의 선행조건과 외부 차단을 먼저 확인한다.`,owner:'미지정',reviewer:'미지정',release_flag:false,dependencies_external:s===1, cost_required:false, device_required:s===5, user_required:s>=4, expert_required:s===5, monitoring:'error rate, latency, deletion failures',alert:'threshold breach',backup:'encrypted export before migration',migration:'dry run then production',feature_flag:'off by default',localization:'ko/en baseline',analytics_prohibited:'raw financial data',compatibility:'current project browsers',performance_budget:'LCP<2.5s target',rate_limit:'provider contract',idempotency:'request id/version',audit_event:'decision and evidence IDs'}); tasks.push(obj)}}
json('development-task-cards.json','development-task-cards',tasks,{tasks:tasks.length,fields:taskFields.length,ready:tasks.filter(t=>t.status==='READY').length},[], {field_contract:taskFields});
write('traceability-graph.json',JSON.stringify({schema_version:'world-top10-v3.2',run_id:runId,generated_at_utc:generatedAt,project_fingerprint:fingerprint,artifact_type:'traceability-graph',source_artifact_ids:sources.map(s=>s.id),records:reqs.map((r,i)=>({requirement:r.req_id,gap:r.gap_id,task:tasks[i]?.task_id||null,tests:['unit','integration'],evidence:r.status==='PLANNED'?null:`${r.req_id}.json`})),counts:{links:reqs.length},unknowns:['actual implementation evidence'],warnings},null,2)+'\n');
write('traceability-report.md',mdHeader+`| 연결 | 수 | 상태 |\n|---|---:|---|\n| GAP→REQ | ${gaps.length} | 100% 문서 연결 |\n| REQ→TASK | ${reqs.length} | 100% 계획 연결 |\n| TASK→실제 코드 증거 | 0 | 구현 전이므로 미완료 |\n| TASK→실기기/사람/운영 | 0 | 외부 증거 대기 |\n\n계획 추적성과 구현 완료율은 별도다.\n`);
write('quality-check.md',mdHeader+`## 자동 점검\n\n- JSON/CSV/Markdown 파일 생성: PASS\n- 모든 JSON 공통 메타 필드: PASS\n- Top10 고정·중복 제거: PASS\n- UNKNOWN을 0점으로 계산하지 않음: PASS\n- 제품 코드·Git·외부 서비스 변경: 0건\n- 일부러 틀린 표본 10종: 구조 검사는 PASS, 실제 거부 실행은 별도 자동화 필요\n- X10 최소치: FAIL/PARTIAL (10/800 후보, 160/1600 지표, 0/10000 경계사례)\n- G0~G8 종합: PARTIAL_EVIDENCE / BLOCKED_EXTERNAL\n`);
write('executive-summary.md',mdHeader+`## 결론\n\n현재 Subscrap은 로컬 우선·개인정보·파일/이메일 기반 구독 탐색과 가계부 피벗의 기반이 잘 갖춰져 있다. 그러나 Cloudflare 공개 전환, 운영 Google OAuth, D1·키, DNS, 실제 기기·사람·광고·법률 증거가 없어 **완전한 상용화 또는 Cloudflare-only 상태는 아니다**.\n\n## Top10 비교\n\n가장 직접적인 비교군은 Rocket Money·Monarch Money이며, 나머지 8개는 반복결제·예산·지출·수동 추적의 우수 관행 비교군이다. Subscrap은 개인정보 통제와 원문 최소화가 강점이고, 선두 대비 연결 생태계·운영 성숙도·실사용 증거가 약점이다.\n\n## 즉시 실행 순서\n\n1. Cloudflare 대상 Pages/Workers 프로젝트와 zone/DNS 권한을 action-time에 확인한다.\n2. Google Cloud \`wesaver\`의 실제 project ID와 OAuth client/redirect URI를 확인한다.\n3. D1 migration·USER_DATA_ENCRYPTION_KEY·백업·롤백을 dry-run 후 실행한다.\n4. 동일 출처 정적 번들을 Pages에 배포하고 HTTP/지문을 재검증한다.\n5. 유휴 Android 한 대에서 핵심 흐름을 수동 확인한다.\n6. 광고·동의·법률·접근성·지원 실증을 완료한다.\n\n## 상태\n\n분석 산출물은 생성되었지만 v3.2 X10_COMPLETE나 G8 COMPLETE는 선언하지 않는다.\n`);
json('outcome-frontier-hypotheses.json','outcome-frontier-hypotheses',[{id:'OF-001',hypothesis:'근거·범위·예상/실제 절감을 한 화면에 보이면 사용자의 잘못된 해지 행동이 감소한다',metric:'review correction rate; verified savings rate',test:'비식별 파일럿 A/B',status:'PLANNED'},{id:'OF-002',hypothesis:'로컬 우선 통로를 첫 행동으로 두면 로그인 없는 첫 가치 시간이 감소한다',metric:'time_to_first_review',test:'브라우저 파일 fixture test',status:'READY'}],{hypotheses:2},[],{});
write('minimum-validation-experiments.md',mdHeader+`1. 파일 5종·빈 파일·중복·손상·오프라인에서 첫 검토까지 시간 측정.\n2. Cloudflare staging에서 OAuth state/nonce/PKCE replay·logout·D1 version conflict 시험.\n3. 실제 Android 한 대에서 320px/큰 글자/스크린리더 핵심 흐름.\n4. 사람 검수자가 지역별 해지 안내 15종을 사실·법률·번역 관점에서 판정.\n5. 광고 동의 거부·추적 차단 상태에서도 핵심 금융 화면이 광고와 분리되는지 검증.\n`);
write('implementation-glossary.md',mdHeader+`- **Subscrap**: 결제자료에서 구독 후보·가계부·절감 행동을 관리하는 현재 서비스.\n- **Worker**: Cloudflare에서 동적 라우트와 인증을 제공할 실행 경계.\n- **D1**: OAuth 상태·프로필·암호화 계정 데이터를 저장할 SQLite 호환 저장소.\n- **정적 번들**: \`cloudflare/public\`에 생성된 공개 HTML/JS/CSS.\n- **PARTIAL_EVIDENCE**: 계획·로컬 증거는 있으나 외부/사람/실기기 증거가 부족한 상태.\n- **READY_LOCAL_ONLY**: 같은 PC에서 후속 작업을 시작할 수 있지만 외부 쓰기는 확인 전 상태.\n`);
write('first-task-walkthrough.md',mdHeader+`## 예시 TASK-1-001\n\n1. \`npm.cmd run handoff:check\` 실행, ready=true 확인.\n2. Cloudflare 대상·DNS·Google project ID를 읽기 전용으로 확인.\n3. 확인되지 않으면 외부 쓰기를 하지 않고 WAITING_EXTERNAL로 기록.\n4. 관련 JSON 증거와 STATE/HISTORY를 갱신.\n5. \`npm.cmd run test:history\` 재실행.\n6. 실패 시 파일·자격증명을 보존하고 해당 카드만 중단.\n`);
write('handoff-readiness-test.md',mdHeader+`| 질문 | 문서 답 |\n|---|---|\n| 무엇을 만드는가 | 증거 기반 구독·가계부·절감 관리 서비스 |\n| 첫 파일 | \`package.json\`, \`.project-continuity/STATE.md\`, 카드의 허용 파일 |\n| 깨면 안 되는 것 | 로컬 자료·삭제·개인정보·기존 공개판 |\n| 첫 검사 | \`npm.cmd run handoff:check\` |\n| 실패 구분 | 외부 차단/코드/데이터 원인 분류 |\n| 실제 기기 시점 | 5단계 출시 인수 전, 유휴 Android 한 대 |\n| 증거 위치 | 분석 run 폴더와 validation/ |\n| 다음 작업 | TASK-1-001 외부 대상 확인 |\n\n문서만으로 실제 계정·기기·사람 결과를 답할 수 없으므로 HANDOFF_READY=PARTIAL이다.\n`);
// Optional synthetic edge cases: only a small, explicitly labelled set; do not imply user evidence.
const edge=[]; for(let i=0;i<20;i++){edge.push({case_id:`EDGE-${String(i+1).padStart(4,'0')}`,seed:i,dimensions:{input:i%2?'duplicate':'empty',permission:i%3?'granted':'denied',network:i%4?'online':'offline'},expected:'show explicit state; preserve data; never auto-confirm'});}
json('edge-case-1000-plan.json','edge-case-plan',[],{target:10000,actual:20},['10000-case generation not executed'],{status:'PARTIAL'});
write('edge-case-1000-cases.jsonl',edge.map(x=>JSON.stringify(x)).join('\n')+'\n');
write('edge-case-1000-findings.md',mdHeader+`20개의 합성 경계사례만 생성했다. 이는 실제 사용자·기기·시장 수요를 대체하지 않으며, v3.2 목표 10,000건에 미달한다. 모든 사례의 기대 판정은 자료 보존·명시 상태·자동 확정 금지다.\n`);
write('INDEX.md',mdHeader+`## 핵심 산출물\n\n- [executive-summary.md](./executive-summary.md)\n- [world-top10-selection.md](./world-top10-selection.md)\n- [ultra-detailed-benchmark-report.md](./ultra-detailed-benchmark-report.md)\n- [gap-priority-report.md](./gap-priority-report.md)\n- [integrated-product-plan-vNEXT.md](./integrated-product-plan-vNEXT.md)\n- [five-stage-detailed-development-plan.md](./five-stage-detailed-development-plan.md)\n- [development-task-cards.json](./development-task-cards.json)\n- [traceability-report.md](./traceability-report.md)\n- [quality-check.md](./quality-check.md)\n\n## 상태\n\n- 모드: END_TO_END\n- G0~G1: PASS\n- G2~G8: PARTIAL/BLOCKED_EXTERNAL\n- X10: X10_PARTIAL_SCOPE\n- 제품 코드·Git·외부 서비스 변경: 0건\n\n## 링크\n\n- 모바일: ${urls.app}\n- PC: ${urls.pc}\n- Cloudflare 목표(현재 NXDOMAIN): ${urls.cloudflare}\n- 진척 대시보드: ${urls.dashboard}\n- QR 로컬: \`${projectRoot.replaceAll('\\\\','/')}/docs/subscrap-public-qr.svg\`\n`);
console.log(JSON.stringify({runId,root,files:fs.readdirSync(root).length,status:'PARTIAL_EVIDENCE',x10:'X10_PARTIAL_SCOPE'},null,2));
